/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList; // Necesario para limpiar tabla en caso de error

/**
 *
 * @author moon1
 */
public class AnaLex extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    /**
     * Creates new form AnaLex
     */
    public AnaLex() {
        initComponents();
        configurarTabla(); // Configurar la tabla después de crear componentes
        setLocationRelativeTo(null);
        this.setTitle("Analizador Léxico");
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /** Configura el DefaultTableModel para la JTable AL_Table. */
    private void configurarTabla() {
        tableModel = new DefaultTableModel(
            new Object[][]{},
            new String [] {"Clase lexica", "Token"} // Nombres de columna
        ) {
            // Hacer que la tabla no sea editable por el usuario
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        AL_Table.setModel(tableModel);
        // Ajustes opcionales
        AL_Table.getColumnModel().getColumn(0).setPreferredWidth(200);
        AL_Table.getColumnModel().getColumn(1).setPreferredWidth(80);
        AL_Table.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKAL_btn = new javax.swing.JButton();
        OutAL_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        Selec_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AL_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AL_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Analizador Léxico");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKAL_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKAL_btn.setText("Aceptar");
        OKAL_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKAL_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKAL_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKAL_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        OutAL_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutAL_btn.setText("Cancelar");
        OutAL_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OutAL_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutAL_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutAL_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Introduzca la expresión regular a analizar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel1.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 330, -1));

        Selec_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carpeta.png"))); // NOI18N
        Selec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selec_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Selec_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seleccione el AFD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        AL_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AL_txtActionPerformed(evt);
            }
        });
        jPanel1.add(AL_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 370, -1));

        AL_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Clase lexica", "Token"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AL_Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 560, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKAL_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKAL_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKAL_btnActionPerformed

    private void OutAL_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutAL_btnActionPerformed
        /*/ Accion para que el boton de salir funcione
        if(evt.getSource()== OutU_btn){
            dispose(); // Cierra la ventana actual

            Views.MainPage inicio = new Views.MainPage(); // Crea la nueva ventana
            Controlers.Controller controller = new Controlers.Controller(inicio); // Asocia el controlador
            inicio.setVisible(true); // Muestra el MainPage
        }*/
    }//GEN-LAST:event_OutAL_btnActionPerformed

    private void Selec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selec_btnActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        // Opcional: establecer el directorio inicial
        fileChooser.setCurrentDirectory(new java.io.File(System.getProperty("user.home")));

        // Mostrar el cuadro de diálogo para abrir archivos
        int resultado = fileChooser.showOpenDialog(this);

        // Si el usuario seleccionó un archivo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = fileChooser.getSelectedFile();

            // Mostrar la ruta completa en el JTextField
            txtRuta.setText(archivoSeleccionado.getAbsolutePath());

            // Si quieres solo el nombre del archivo:
            // txtRuta.setText(archivoSeleccionado.getName());
        }
    }//GEN-LAST:event_Selec_btnActionPerformed

    private void AL_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AL_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AL_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public JButton getBotonOK() { return OKAL_btn; }
    public JButton getBotonCancelar() { return OutAL_btn; }
    public JButton getBotonSeleccionar() { return Selec_btn; }

    public String getRutaAFD() { return txtRuta.getText(); }
    public void setRutaAFD(String ruta) { txtRuta.setText(ruta); }

    public String getExpresion() { return AL_txt.getText(); }
    public void setExpresion(String expresion) { AL_txt.setText(expresion); }

    /** Devuelve el campo de texto de expresión para añadir listeners (ej. Enter). */
    public JTextField getCampoExpresion() { return AL_txt; }

    /**
     * Limpia la tabla y la llena con los resultados del análisis léxico.
     * @param data Lista de Object[], donde cada array es una fila: { String Lexema, int TokenID }
     */
    public void setTablaResultados(List<Object[]> data) {
        tableModel.setRowCount(0); // Limpiar tabla
        if (data != null) {
            for (Object[] rowData : data) {
                if (rowData != null && rowData.length >= 2) {
                    tableModel.addRow(rowData);
                }
            }
        } else {
             // Opcional: Limpiar tabla si data es null
             tableModel.setRowCount(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AL_Table;
    public javax.swing.JTextField AL_txt;
    public javax.swing.JButton OKAL_btn;
    public javax.swing.JButton OutAL_btn;
    private javax.swing.JButton Selec_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
