/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.*;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author moon1
 */
public class CerrP extends javax.swing.JFrame {
    
    public CerrP() { // <-- Constructor corregido
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Cerradura Positiva (+)");
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        // this.repaint(); // No necesario aquí
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CP_box = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        OKCP_btn = new javax.swing.JButton();
        OutP_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cerradura +");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Aplicar a:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        CP_box.setBackground(new java.awt.Color(255, 255, 255));
        CP_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CP_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CP_boxActionPerformed(evt);
            }
        });
        jPanel1.add(CP_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CerrP.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 70));

        OKCP_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKCP_btn.setText("Aceptar");
        OKCP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKCP_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKCP_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        OutP_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutP_btn.setText("Cancelar");
        OutP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutP_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutP_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKCP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKCP_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKCP_btnActionPerformed

    private void OutP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutP_btnActionPerformed
        
    }//GEN-LAST:event_OutP_btnActionPerformed

    private void CP_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CP_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CP_boxActionPerformed

    public JButton getBotonOK() { return OKCP_btn; }
    public JButton getBotonCancelar() { return OutP_btn; }

    /** Obtiene el ID del AFN seleccionado en el ComboBox. */
    public String getAutomataSeleccionado() {
        Object selected = CP_box.getSelectedItem();
        return (selected != null) ? selected.toString() : null;
    }

    /** Puebla el ComboBox con la lista de IDs de AFN disponibles. */
    public void setListaAutomatas(List<String> items) {
        String[] itemsArray = items.toArray(new String[0]);
        CP_box.setModel(new DefaultComboBoxModel<>(itemsArray));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CP_box;
    public javax.swing.JButton OKCP_btn;
    public javax.swing.JButton OutP_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
