/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.*;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author moon1
 */
public class CerrK extends javax.swing.JFrame {
    
    public CerrK() { // <-- Constructor corregido
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Cerradura Kleene (*)");
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        // this.repaint(); // No necesario aquí
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKK_btn = new javax.swing.JButton();
        OutK_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        K_box = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cerradura *");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKK_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKK_btn.setText("Aceptar");
        OKK_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKK_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKK_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        OutK_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutK_btn.setText("Cancelar");
        OutK_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutK_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutK_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Aplicar a:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        K_box.setBackground(new java.awt.Color(255, 255, 255));
        K_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(K_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CerrK (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKK_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKK_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKK_btnActionPerformed

    private void OutK_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutK_btnActionPerformed
        
    }//GEN-LAST:event_OutK_btnActionPerformed

    public JButton getBotonOK() { return OKK_btn; }
    public JButton getBotonCancelar() { return OutK_btn; }

    /** Obtiene el ID del AFN seleccionado en el ComboBox. */
    public String getAutomataSeleccionado() {
        Object selected = K_box.getSelectedItem();
        return (selected != null) ? selected.toString() : null;
    }

    /** Puebla el ComboBox con la lista de IDs de AFN disponibles. */
    public void setListaAutomatas(List<String> items) {
        String[] itemsArray = items.toArray(new String[0]);
        K_box.setModel(new DefaultComboBoxModel<>(itemsArray));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> K_box;
    public javax.swing.JButton OKK_btn;
    public javax.swing.JButton OutK_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
