/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author moon1
 */
public class ShowAFN extends javax.swing.JFrame {
    
    private DefaultTableModel tableModel;

    public ShowAFN() {
        initComponents();
        configurarTabla(); // Configurar la tabla
        setLocationRelativeTo(null);
        this.setTitle("Lista de AFNs Creados");
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /** Configura el DefaultTableModel para la JTable jTable1. */
    private void configurarTabla() {
        // *** CAMBIADO: Añadida columna "Token(s)" ***
        tableModel = new DefaultTableModel(
            new Object[][]{},
            new String [] {"ID del Autómata", "Representación", "Token(s)"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // No editable
            }
        };
        jTable1.setModel(tableModel);
        
        // Ajustes opcionales
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100); // Tamaño para tokens
        jTable1.getTableHeader().setReorderingAllowed(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OutAL_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mostrar lista de AFN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OutAL_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutAL_btn.setText("Regresar");
        OutAL_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OutAL_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutAL_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutAL_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Posición en la lista", "AFN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 560, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OutAL_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutAL_btnActionPerformed
        /*/ Accion para que el boton de salir funcione
        if(evt.getSource()== OutU_btn){
            dispose(); // Cierra la ventana actual

            Views.MainPage inicio = new Views.MainPage(); // Crea la nueva ventana
            Controlers.Controller controller = new Controlers.Controller(inicio); // Asocia el controlador
            inicio.setVisible(true); // Muestra el MainPage
        }*/
    }//GEN-LAST:event_OutAL_btnActionPerformed

    public JButton getBotonRegresar() {
        return OutAL_btn;
    }

    /**
     * Limpia la tabla y la llena con los datos proporcionados por el Controller.
     * @param data Lista de Object[], donde cada array es una fila:
     * { String idAFN, String representacionAFN, String tokens }
     */
    public void setTablaAutomatas(List<Object[]> data) {
        tableModel.setRowCount(0); // Limpiar tabla
        if (data != null) {
            for (Object[] rowData : data) {
                 if (rowData != null && rowData.length >= 3) { // *** CAMBIADO a >= 3 ***
                    tableModel.addRow(rowData);
                 }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton OutAL_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
