/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.*;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author moon1
 */
public class Unir extends javax.swing.JFrame {
    
    public Unir() { // <-- Constructor corregido
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Unir Autómatas (OR)");
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        // this.repaint(); // No necesario aquí
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKU_btn = new javax.swing.JButton();
        OutU_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        U1_box = new javax.swing.JComboBox<>();
        U2_box = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Unir ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKU_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKU_btn.setText("Aceptar");
        OKU_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKU_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKU_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        OutU_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutU_btn.setText("Cancelar");
        OutU_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutU_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutU_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Union.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 70));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Con:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Unir AFN:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        U1_box.setBackground(new java.awt.Color(255, 255, 255));
        U1_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(U1_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 180, 30));

        U2_box.setBackground(new java.awt.Color(255, 255, 255));
        U2_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(U2_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKU_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKU_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKU_btnActionPerformed

    private void OutU_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutU_btnActionPerformed
        
    }//GEN-LAST:event_OutU_btnActionPerformed

    public JButton getBotonOK() { return OKU_btn; }
    public JButton getBotonCancelar() { return OutU_btn; }

    /** Obtiene el ID del AFN seleccionado en el primer ComboBox. */
    public String getAutomata1Seleccionado() {
        Object selected = U1_box.getSelectedItem();
        return (selected != null) ? selected.toString() : null;
    }

    /** Obtiene el ID del AFN seleccionado en el segundo ComboBox. */
    public String getAutomata2Seleccionado() {
        Object selected = U2_box.getSelectedItem();
        return (selected != null) ? selected.toString() : null;
    }

    /** Puebla ambos ComboBox con la lista de IDs de AFN disponibles. */
    public void setListaAutomatas(List<String> items) {
        String[] itemsArray = items.toArray(new String[0]);
        U1_box.setModel(new DefaultComboBoxModel<>(itemsArray));
        U2_box.setModel(new DefaultComboBoxModel<>(itemsArray));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton OKU_btn;
    public javax.swing.JButton OutU_btn;
    public javax.swing.JComboBox<String> U1_box;
    public javax.swing.JComboBox<String> U2_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
